name: Docker
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  GH_REGISTRY: ghcr.io
  DH_REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag
        run: |
          git fetch --tags
          echo "current_tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
          echo "latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Only
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push (main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          tags: ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:unstable

      - name: Build and Push (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          tags: |
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.latest_tag == env.current_tag && env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Logout of GitHub Container Registry
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        run: docker logout ${{ env.GH_REGISTRY }}

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DH_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          tags: ${{ env.DH_REGISTRY }}/${{ env.IMAGE_NAME }}:unstable

      - name: Build and Push (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          tags: |
            ${{ env.DH_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.latest_tag == env.current_tag && env.DH_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
